# Generated by Django 4.1.7 on 2023-04-01 01:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="activities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("TRANSPORTATION", "Transportation"),
                        ("SHOPPING", "Shopping"),
                        ("HOME_VISIT", "Home Visit"),
                        ("TECHNOLOGY_ASSISTANCE", "Technology Assistance"),
                        ("MENTAL_HEALTH_SUPPORT", "Mental Health Support"),
                    ],
                    max_length=255,
                ),
                blank=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name="provider",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
