# Generated by Django 4.1.7 on 2023-04-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0002_alter_provider_activities_alter_provider_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="profile_photo",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
