# Generated by Django 4.1.7 on 2023-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0004_alter_provider_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="age",
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provider",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                default="MALE",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provider",
            name="max_distance",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
