version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB_NAME: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${PWD}/services/db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx
    volumes:
      - ${PWD}/services/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - rest
      - client

  client:
    build:
      context: ${PWD}/services/client
    environment:
      VITE_REST_URL: ${VITE_REST_URL}
    volumes:
      - ${PWD}/services/client/:/app
      - /app/node_modules
    entrypoint: ["npm", "run", "dev"]
    depends_on:
      - rest

  rest:
    build:
      context: ${PWD}/services/rest
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_TEST_NAME: ${DB_TEST_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/services/rest/:/app
    entrypoint: ["./docker-entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
